
spring:
  application:
    name: AuthService
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: AuthServiceAuthServiceAuthServiceAuthServiceAuthServiceAuthServiceAuthServiceAuthService
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
